{
 "title": "http-server-projeto-korp",
 "tags": [ "projeto-korp" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Disponibilidade do Serviço",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "service_up", "legendFormat": "Status" }
   ]
  },
  {
   "title": "Total de Requisições",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{path=\"/projeto-korp\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Taxa de Requisições por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{path=\"/projeto-korp\"}[1m])",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Taxa de Req/s (último 1m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{path=\"/projeto-korp\"}[1m]))",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "Requisições com Sucesso (200)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{path=\"/projeto-korp\",status=\"200\"})",
     "legendFormat": "200 OK"
    }
   ]
  },
  {
   "title": "Volume de Requisições por Status HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_requests_total{path=\"/projeto-korp\"}[1m]))",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  }
 ]
}